<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\libs\Kokoabim.CommandLineInterface\src\Kokoabim.CommandLineInterface\Kokoabim.CommandLineInterface.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <AssemblyName>gt</AssemblyName>
        <RootNamespace>Kokoabim.GitTasks</RootNamespace>

        <AssemblyVersion>1.1.0</AssemblyVersion>
        <FileVersion>1.1.0</FileVersion>
        <InformationalVersion>1.1.0</InformationalVersion>

        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>

        <Company>Spencer James</Company>
        <Authors>Spencer James</Authors>
        <Product>Git Tasks</Product>
        <Description>Console tool for performing various Git CLI tasks</Description>
        <Copyright>Copyright © Spencer James 2025-2026</Copyright>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
